// Generated by CoffeeScript 1.3.3
(function() {
  var ContentAddressable, computeHash;

  computeHash = require('sha1');

  ContentAddressable = (function() {

    function ContentAddressable(_arg) {
      this.store = _arg.store;
    }

    ContentAddressable.prototype.write = function(data, cb) {
      var hash;
      hash = computeHash(data);
      this.store.write(hash, data);
      if (cb) {
        return cb(null, hash);
      } else {
        return hash;
      }
    };

    ContentAddressable.prototype.read = function(hash, cb) {
      return this.store.read(hash, cb);
    };

    return ContentAddressable;

  })();

  module.exports = ContentAddressable;

}).call(this);
