// Generated by CoffeeScript 1.3.3
(function() {
  var ContentAddressableStore, computeHash;

  computeHash = require('sha1');

  ContentAddressableStore = (function() {

    function ContentAddressableStore(store) {
      this.store = store;
    }

    ContentAddressableStore.prototype.write = function(data, cb) {
      var hash;
      hash = computeHash(data);
      this.store.write(hash, data);
      if (cb) {
        return cb(null, hash);
      } else {
        return hash;
      }
    };

    ContentAddressableStore.prototype.read = function(hash, cb) {
      return this.store.read(hash, cb);
    };

    return ContentAddressableStore;

  })();

  module.exports = ContentAddressableStore;

}).call(this);
